-- Existing employee account details table for TM-HR-Pulse.
-- Run this only if the employees table is missing columns or RLS policies.

create table if not exists public.employees (
  id int8 generated by default as identity primary key,
  name text,
  email text,
  department text,
  role text,
  joining_date date
);

alter table public.employees
  add column if not exists name text;

alter table public.employees
  add column if not exists email text;

alter table public.employees
  add column if not exists department text;

alter table public.employees
  add column if not exists role text;

alter table public.employees
  add column if not exists joining_date date;

alter table public.employees enable row level security;

drop policy if exists "Anyone can create employee account details" on public.employees;
drop policy if exists "Authenticated users can read employee account details" on public.employees;

create policy "Anyone can create employee account details"
on public.employees
for insert
to anon, authenticated
with check (true);

create policy "Authenticated users can read employee account details"
on public.employees
for select
to authenticated
using (true);

create index if not exists employees_email_idx on public.employees (email);
